namespace InsightFlow.Nl2Sql.Models;

/// <summary>
/// Represents a graph / visualization recommendation generated by the LLM,
/// structured specifically for Chart.js in Angular frontends.
/// </summary>
public record ChartRecommendation(
    string ChartType,
    string Title,
    string XAxisColumn,
    List<string> YAxisColumns,
    string? Reasoning = null);
